apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: coturn
  name: coturn
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        app: coturn
    spec:
      containers:
      - env:
        - name: DB_NAME
          value: "0"
        - name: DB_PASSWORD
          value: TROOD
        - name: MAX_PORT
          value: "65535"
        - name: MIN_PORT
          value: "57001"
        - name: REDIS_IP
          value: 127.0.0.1
        - name: TURN_LISTEN_PORT
          value: "3478"
        image: openvidu/openvidu-coturn:1.0.0
        name: coturn
    restartPolicy: OnFailure
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: kms
  name: kms
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kms
    spec:
      containers:
      - env:
        - name: KMS_MAX_PORT
          value: "57000"
        - name: KMS_MIN_PORT
          value: "40000"
        image: kurento/kurento-media-server:6.14.0
        name: kms
        ports:
          - containerPort: 8888
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: openvidu-server
  name: openvidu-server
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        app: openvidu-server
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - export COTURN_IP=`/usr/local/bin/discover_my_public_ip.sh`; /usr/local/bin/entrypoint.sh
        env:
        - name: COTURN_REDIS_IP
          value: 127.0.0.1
        - name: COTURN_REDIS_PASSWORD
          value: TROOD
        - name: KMS_URIS
          value: '["ws://localhost:8888/kurento"]'
        - name: SERVER_PORT
          value: "5443"
        - name: SERVER_SSL_ENABLED
          value: "false"
        image: openvidu/openvidu-server:2.15.0-beta1
        name: openvidu-server
      restartPolicy: OnFailure
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - env:
        - name: REDIS_PASSWORD
          value: TROOD
        image: openvidu/openvidu-redis:1.0.0
        name: redis
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: eme-dev.saas.trood.ru
    http:
      paths:
      - path: /webrtc
        backend:
          serviceName: openvidu-server
          servicePort: 5443
